home:
    path: /
    controller: App\Controller\HomeController::index

offers:
    path: /offres
    controller: App\Controller\OfferController::index


offer_show:
    path: /offres/{slug}-{id}
    controller: App\Controller\OfferController::show
    requirements:
        slug: ([a-z0-9\-]*)


